### PR TITLE
Add badge prop on app element, mapped to setBadge

### PR DESCRIPTION
**Pull request by MarshallOfSound**
This is mostly just me getting familiar with how all this works, it's a pretty cool project.

This adds a new prop on the `app` element for `badge`, let me know if I've done this right as I'm completely new to React Fiber 😄 

All that said I'd like to float an idea here RE the the `dock` API's, I think in the future all the `app.dock` API's should be on there on element. Kind of like this

```js
<app>
  <dock />
</app>
```

It would have to be a direct child of `app` and you can only have one mounted at a time.  Then you can map the following

* `bouncing` - String prop to indicate bouncing state, removal of prop will cancel bounce
* `icon` - The icon for the dock
* `menu` - A menu element structure 😄   Not sure if this should be a prop of dock or a child element of dock
* And then finally if the dock element is mounted or not can be mapped to the `show` and `hide` methods of `dock`.  So an absence of the element would hide the dock Etc.

For now though let's just look at this PR and if the above sounds good / needs discussion I can raise an issue for it 👍

### CODE REVIEW

**Comment by mhink** [comment]
So, the description in the latter half of your comment is actually *exactly* how I imagined a <dock/> element working. Mad props, yo!

Do you think you could make a first pass at an implementation of such an element (DockElement, maybe?), with just the "bouncing" and "badge" props? That'd be a really good start for the dock menu pattern you described (which I'm definitely down to work on as well.)

**Comment by MarshallOfSound** [comment]
@mhink Great to hear, I'll give that dock element a go 👍

**Comment by MarshallOfSound** [comment]
@mhink Gave it a shot, got those props working and the dock hide/show state is mapped to the presence of a dock element in the app container 👍 

Let me know what you think 😄

**Comment by MarshallOfSound** [comment]
Closing as stale

**Pull request closed without merging**
